name: mirror_Test
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'https://github.com/roberluna/demo-frontend.git'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.PAT }}
